In [7]:
import pandas as pd
import numpy as np
import random
import os
import csv
df_csv_append=pd.DataFrame()

In [8]:
csv_path=os.path.join("cb_05_01.csv")
org_df=pd.read_csv(csv_path)
org_df.head(10)

C:\Users\chaoh\AppData\Local\Temp\ipykernel_20832\499226871.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  org_df=pd.read_csv(csv_path)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FE6A074FC945A086,electric_bike,2024-05-01 08:05:53,2024-05-01 08:15:14,1 Ave & E 30 St,6079.03,E 74 St & 1 Ave,6953.08,40.741509,-73.975355,40.768974,-73.954823,member
1,6844CF42F72827D7,classic_bike,2024-05-10 15:00:06,2024-05-10 15:08:58,31 Ave & 57 St,6621.06,31 Ave & Steinway St,6782.01,40.757357,-73.904726,40.761149,-73.917007,member
2,D7C9E007F791A7A2,classic_bike,2024-05-06 12:28:39,2024-05-06 12:35:21,E 89 St & 3 Ave,7265.10,E 80 St & 2 Ave,7121.02,40.780628,-73.952167,40.773914,-73.954395,member
3,3419650E2F5999F1,classic_bike,2024-05-16 16:09:14,2024-05-16 16:14:20,E 89 St & 3 Ave,7265.10,E 80 St & 2 Ave,7121.02,40.780628,-73.952167,40.773914,-73.954395,member
4,5469FDC75E0F1FCA,electric_bike,2024-05-29 15:43:37,2024-05-29 15:49:27,1 Ave & E 30 St,6079.03,E 45 St & 3 Ave,6464.08,40.741444,-73.975361,40.752554,-73.972826,member
5,771438887ADBA23D,electric_bike,2024-05-10 17:25:27,2024-05-10 17:41:38,1 Ave & E 30 St,6079.03,E 74 St & 1 Ave,6953.08,40.741602,-73.975315,40.768974,-73.954823,member
6,8D0709918C276FDC,classic_bike,2024-05-31 16:12:47,2024-05-31 16:40:34,Cumberland St & Lafayette Ave,4428.02,Hart St & Wyckoff Ave,4971.01,40.687534,-73.972652,40.704876,-73.919911,member
7,B4ECBEB2D12AE451,electric_bike,2024-05-28 14:20:27,2024-05-28 14:22:11,E 47 St & 1 Ave,6498.09,E 45 St & 3 Ave,6464.08,40.752155,-73.968003,40.752554,-73.972826,member
8,1265629F414BCE14,electric_bike,2024-05-31 12:38:42,2024-05-31 12:42:42,E 89 St & 3 Ave,7265.10,E 80 St & 2 Ave,7121.02,40.780671,-73.952263,40.773914,-73.954395,member
9,25D6E172C7393E21,classic_bike,2024-05-26 15:38:27,2024-05-26 15:42:19,31 Ave & 57 St,6621.06,62 St & Northern Blvd,6536.02,40.757357,-73.904726,40.754176,-73.900318,member

In [9]:
#read all data set 1-5
df1=pd.read_csv('cb_05_01.csv')
df2=pd.read_csv('cb_05_02.csv')
df3=pd.read_csv('cb_05_03.csv')
df4=pd.read_csv('cb_05_04.csv')
df5=pd.read_csv('cb_05_05.csv')

combined_df = pd.concat([df1,df2, df3, df4, df5], ignore_index=True)
combined_df.to_csv('combined.csv',index=False)

C:\Users\chaoh\AppData\Local\Temp\ipykernel_20832\1862456302.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv('cb_05_01.csv')
C:\Users\chaoh\AppData\Local\Temp\ipykernel_20832\1862456302.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv('cb_05_02.csv')
C:\Users\chaoh\AppData\Local\Temp\ipykernel_20832\1862456302.py:4: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df3=pd.read_csv('cb_05_03.csv')
C:\Users\chaoh\AppData\Local\Temp\ipykernel_20832\1862456302.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df4=pd.read_csv('cb_05_04.csv')
C:\Users\chaoh\AppData\Local\Temp\ipykernel_20832\1862456302.py:6: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df5=pd.read_csv('cb_05_05.csv')

In [10]:
print(combined_df.dtypes)

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [12]:
## Count rider id
#count_ride_id=combined_df["ride_id"].value_counts()
#count_ride_id_df=pd.DataFrame(count_ride_id,items(),column=["unique_values","Counts"])
#count_ride_id_df

NameError: name 'items' is not defined

In [21]:
#Take random sample
sample_size=150000
sample_data=combined_df.sample(n=sample_size)
sample_data.head(10)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
2509571,1E0471B13578A5CB,classic_bike,2024-05-25 18:54:58,2024-05-25 19:15:49,W 45 St & 8 Ave,6676.02,Riverside Blvd & W 67 St,7183.03,40.759291,-73.988597,40.777507,-73.988886,casual
3015726,751BD2919F855099,electric_bike,2024-05-08 17:15:13,2024-05-08 17:26:20,E 44 St & 2 Ave,6422.09,St Marks Pl & 1 Ave,5626.13,40.751236,-73.972079,40.727791,-73.985649,member
3875460,A327924D8296E37F,electric_bike,2024-05-17 10:39:35,2024-05-17 10:48:43,Columbus Ave & W 72 St,7175.05,E 81 St & York Ave,7084.12,40.776888,-73.979151,40.772838,-73.949892,member
4191239,D957A9E5AEE5E932,classic_bike,2024-05-13 14:40:03,2024-05-13 14:45:09,Great Jones St,5636.11,1 Ave & E 6 St,5626.15,40.727434,-73.993790,40.726331,-73.986169,member
2029805,31AF04369A04A428,electric_bike,2024-05-08 15:33:46,2024-05-08 15:45:04,E 161 St & River Ave,8041.07,E 163 St & Tiffany St,7927.08,40.827941,-73.927199,40.821075,-73.895069,member
3399156,79510DCCFD095138,electric_bike,2024-05-14 07:16:41,2024-05-14 07:25:34,Gansevoort St & Hudson St,6072.16,6 Ave & W 45 St,6593.15,40.739358,-74.004886,40.756951,-73.982631,member
3503620,824E859FCF5042CC,classic_bike,2024-05-12 17:56:38,2024-05-12 18:05:26,Broadway & E 14 St,5905.12,Rivington St & Chrystie St,5453.01,40.734546,-73.990741,40.721101,-73.991925,member
384857,11429ADF9B3F18C1,electric_bike,2024-05-06 16:56:43,2024-05-06 17:01:06,Lafayette Ave & Classon Ave,4452.01,Fulton St & Irving Pl,4263.12,40.689033,-73.960195,40.681860,-73.959432,member
2693340,0986B0C104510167,classic_bike,2024-05-25 15:25:45,2024-05-25 15:37:54,9 Ave & W 45 St,6717.06,Broadway & W 61 St,7014.12,40.760193,-73.991255,40.770030,-73.981968,member
2187274,404F63DEE1AAA76D,classic_bike,2024-05-22 16:17:21,2024-05-22 16:27:00,7 Ave & Central Park South,6912.01,W 31 St & 7 Ave,6331.01,40.766741,-73.979069,40.749156,-73.991600,member

In [22]:
sample_data.to_csv('cb05.csv',index=False)